/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2014 PrismTech
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE
 *
 *   for full copyright notice and license terms.
 *
 */

module VortexGrove {

    struct AnalogueSensor {
        short		id;           
        float		rValue;         
		float		value;
    };
#pragma keylist AnalogueSensor id

	struct LED {
		short	id;
		boolean on;
	};
#pragma keylist LED id

};



