package VortexGrove;


/**
* VortexGrove/AnalogueSensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VortexGrove.idl
* Friday, 20 January 2017 17:26:48 o'clock GMT
*/

/**
* Updated by idl2j
* from VortexGrove.idl
* Friday, 20 January 2017 17:26:49 o'clock GMT
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "AnalogueSensor",
    keys = {"id"}
)
public final class AnalogueSensor implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public float rValue = (float)0;
  public float value = (float)0;

  public AnalogueSensor ()
  {
  } // ctor

  public AnalogueSensor (short _id, float _rValue, float _value)
  {
    id = _id;
    rValue = _rValue;
    value = _value;
  } // ctor

} // class AnalogueSensor
