package VortexGrove;


/**
* VortexGrove/AnalogueSensorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VortexGrove.idl
* Friday, 20 January 2017 17:26:48 o'clock GMT
*/

abstract public class AnalogueSensorHelper
{
  private static String  _id = "IDL:VortexGrove/AnalogueSensor:1.0";

  public static void insert (org.omg.CORBA.Any a, VortexGrove.AnalogueSensor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static VortexGrove.AnalogueSensor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rValue",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_float);
          _members0[2] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (VortexGrove.AnalogueSensorHelper.id (), "AnalogueSensor", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static VortexGrove.AnalogueSensor read (org.omg.CORBA.portable.InputStream istream)
  {
    VortexGrove.AnalogueSensor value = new VortexGrove.AnalogueSensor ();
    value.id = istream.read_short ();
    value.rValue = istream.read_float ();
    value.value = istream.read_float ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, VortexGrove.AnalogueSensor value)
  {
    ostream.write_short (value.id);
    ostream.write_float (value.rValue);
    ostream.write_float (value.value);
  }

}
