package VortexGrove;


/**
* VortexGrove/LED.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VortexGrove.idl
* Friday, 20 January 2017 17:26:48 o'clock GMT
*/

/**
* Updated by idl2j
* from VortexGrove.idl
* Friday, 20 January 2017 17:26:49 o'clock GMT
*/

import com.prismtech.cafe.dcps.keys.KeyList;

@KeyList(
    topicType = "LED",
    keys = {"id"}
)
public final class LED implements org.omg.CORBA.portable.IDLEntity
{
  public short id = (short)0;
  public boolean on = false;

  public LED ()
  {
  } // ctor

  public LED (short _id, boolean _on)
  {
    id = _id;
    on = _on;
  } // ctor

} // class LED
