package VortexGrove;

/**
* VortexGrove/LEDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VortexGrove.idl
* Friday, 20 January 2017 17:26:48 o'clock GMT
*/

public final class LEDHolder implements org.omg.CORBA.portable.Streamable
{
  public VortexGrove.LED value = null;

  public LEDHolder ()
  {
  }

  public LEDHolder (VortexGrove.LED initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VortexGrove.LEDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VortexGrove.LEDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VortexGrove.LEDHelper.type ();
  }

}
